import { Header } from '@/components/molecules/Header/Header';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // user Data fetch
  const user = {
    id: '0',
    name: 'student',
    email: 'example@email.com',
    faculty: 'infomatics',
    year: 4,
  };
  user;
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header user={user} />
        {children}
      </body>
    </html>
  );
}
