import { Header } from '@/components/molecules/Header/Header';
import './globals.css';
import { Inter } from 'next/font/google';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const getUser = async () => {
  const res = await fetch('http://localhost:3000/api/user');
  if (!res.ok) {
    throw new Error('error');
  }

  const user = await res.json();
  console.log(user);

  return user as { id: string; name: string; email: string };
};
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // user Data fetch after the authentication
  // useEffectを使用する必要があるならheaderコンポーネントでuseEffectしてuserの変更を検知し，
  // dropdownにauth済みユーザを反映する
  const user = await getUser();

  return (
    <html lang='en' className="max-w-screen overflow-x-hidden">
      <body className={inter.className}>
        <Suspense fallback='loading...'>
          <Header user={user} />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
