name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest

    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          # 必要に応じて pnpm のバージョンを変更してください
          version: 7.28.0
      - run: pnpm i --frozen-lockfile
        # 👇 Adds Chromatic as a step in the workflow
      - id: react
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          buildScriptName: 'build-storybook'
